"""empty message

Revision ID: 80a70da926c1
Revises: c5c6dd870152
Create Date: 2017-01-13 11:58:59.688728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a70da926c1'
down_revision = 'c5c6dd870152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_association_table',
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], )
    )
    op.create_table('exercise_association_table',
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], )
    )
    op.drop_constraint(u'exercises_day_id_fkey', 'exercises', type_='foreignkey')
    op.drop_column(u'exercises', 'day_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'exercises', sa.Column('day_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'exercises_day_id_fkey', 'exercises', 'days', ['day_id'], ['id'])
    op.drop_table('exercise_association_table')
    op.drop_table('day_association_table')
    # ### end Alembic commands ###
